import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

/* 
 * Gets the Font in the NextJS Application
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/*
 * @Functionality:
 * @par1 : Title of the NextJS Application
 * 
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/*
 * RootLayout because it is present in the root folder
 * It has children.
 */
export default function RootLayout(
  {
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        {/* Some Components which will be there in entire website 
          * can be written here like NavBar, Footer, etc.
         */}
        <div className="border-b p-4">
          Quizio
        </div>

        {/* Children Will rendered in the NextJS app */}
        {children}

      </body>
    </html>
  );
}
